### ISSUE TITLE
Please double check you have all the required session delivery resources 

### ISSUE THREAD

**Issue by carlotta94c** [microsoft/aitour-ecommerce-app-with-ai#8]
Please double check you have all the required resources to deliver this session:
- [x] Main ppt file
- [x] Links to localized versions (when available)
- [x] Presentation recording 
- [x] Silent recording/screen cap only of ALL demos
- [x] Any deployment instructions

**Comment by carlotta94c** [comment]
@elbruno I know you have the demo recordings embedded in the ppt, can you please add them in the session delivery readme file also? Also, I couldn't find Azure resources provisioning instructions.

**Comment by blackgrey0010** [comment]
Did this get resolved? @elbruno @carlotta94c 

Please close issue if this is completed.

**Comment by elbruno** [comment]
Yes this is solved.
Closing the issue.
